<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<AnalysisLevel>latest</AnalysisLevel>
		<InvariantGlobalization>false</InvariantGlobalization>
		<RootNamespace>$(MSBuildProjectName)</RootNamespace>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>
	<ItemGroup Condition="'$(MSBuildProjectExtension)' != '.dcproj'">
		<PackageReference Include="SonarAnalyzer.CSharp">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
</Project>