using System.Collections.Immutable;
using System.Text;
using HotelMigrationCache.SourceGen.Attributes;
using HotelMigrationCache.SourceGen.DiagnosticExtensions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HotelMigrationCache.SourceGen;

[Generator]
public class BinarySerializerGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsSyntaxTargetForGeneration(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx)
            )
            .Where(static m => m is not null)
            .Collect();

        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations);

        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Right!, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        if (node is not ClassDeclarationSyntax classDeclarationSyntax)
            return false;

        return classDeclarationSyntax.AttributeLists.Count > 0;
    }

    private static ClassSerializationInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext ctx)
    {
        var classDeclaration = (ClassDeclarationSyntax)ctx.Node;
        var semanticModel = ctx.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration);

        if (classSymbol is null)
            return null;

        var hasAttribute = classSymbol.GetAttributes()
            .Any(attr => attr.AttributeClass?.Name == nameof(GenerateBinarySerializerAttribute));

        if (!hasAttribute)
            return null;

        var properties = GetPublicProperties(classSymbol);

        return new ClassSerializationInfo(
            classSymbol.Name,
            classSymbol.ContainingNamespace?.ToString() ?? "global",
            GetClassModifiers(classDeclaration),
            properties,
            classSymbol.ToString(),
            classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword)
        );
    }

    private static void Execute(ImmutableArray<ClassSerializationInfo> classes, SourceProductionContext context)
    {
        if (classes.IsDefaultOrEmpty)
            return;

        var validClasses = classes.Where(c => c is not null).ToList();

        foreach (var classInfo in validClasses)
        {
            if (classInfo is null || !classInfo.IsPartial)
            {
                context.ReportDiagnostic(Diagnostic.Create(MyDiagConsts.BS001, Location.None, classInfo?.ClassName ?? "Unknown"));
                continue;
            }

            if (!classInfo.Properties.Any())
            {
                context.ReportDiagnostic(Diagnostic.Create(MyDiagConsts.BS002, Location.None, classInfo.ClassName));
                continue;
            }

            var sourceCode = GenerateSerializationCode(classInfo);
            context.AddSource($"{classInfo.ClassName}.BinarySerializer.g.cs", sourceCode);
        }
    }

    private static string GenerateSerializationCode(ClassSerializationInfo classInfo)
    {
        var namepaceDeclaration = string.IsNullOrEmpty(classInfo.Namespace)
            ? ""
            : $"namespace {classInfo.Namespace}";

        var serializeMethod = GenerateSerializeMethod(classInfo);
        var deserializeMethod = GenerateDeserializeMethod(classInfo);

        return $@"
        // <auto-generated/>
        #nullable enable

        using System;
        using System.IO;
        using System.Text;

        {namepaceDeclaration}
        {{
            {classInfo.Modifiers} partial class {classInfo.ClassName}
            {{
                /// <summary>
                /// Этот метод должен напрямую писать байты свойств в поток (например, используя BinaryWriter)
                /// </summary>
                public void SerializeToBinary(Stream stream)
                {{
                    if(stream == null)
                        throw new ArgumentNullException(nameof(stream));

                    if(!stream.CanWrite)
                        throw new ArgumentNullException(""Stream is not writeable"", nameof(stream));

                    using var writer = new BinaryWriter(stream, Encoding.UTF8, leaveOpen: true);

                    try
                    {{
                        {serializeMethod}
                    }}
                    catch(Exception ex)
                    {{
                        throw new InvalidOperationException($""Failed to serialize {classInfo.ClassName}: {{ex.Message}}"", ex);
                    }}
                }}

                /// <summary>
                /// Deserializes the object from a binary stream
                /// </summary>
                public static {classInfo.ClassName} DeserializeFromBinary(Stream stream)
                {{
                    if (stream == null) 
                        throw new ArgumentNullException(nameof(stream));
        
                    if (!stream.CanRead)
                        throw new ArgumentException(""Stream is not readable"", nameof(stream));

                    using var reader = new BinaryReader(stream, Encoding.UTF8, leaveOpen: true);
                    var result = new {classInfo.ClassName}();

                    try
                    {{
                        {deserializeMethod}
                        return result;
                    }}
                    catch (Exception ex)
                    {{
                        throw new InvalidOperationException($""Failed to deserialize {classInfo.ClassName}: {{ex.Message}}"", ex);
                    }}
                }}
            }}
        }}
        ";
    }

    private static object GenerateDeserializeMethod(ClassSerializationInfo classInfo)
    {
        var sb = new StringBuilder();

        foreach (var property in classInfo.Properties)
        {
            var readCode = GetReadCode(property);
            sb.AppendLine($"{readCode}");
        }

        return sb.ToString();
    }

    private static object GenerateSerializeMethod(ClassSerializationInfo classInfo)
    {
        var sb = new StringBuilder();

        foreach (var property in classInfo.Properties)
        {
            var writeCode = GetWriteCode(property);
            sb.AppendLine($"{writeCode}");
        }

        return sb.ToString();
    }

    private static string GetWriteCode(PropertyInfo property) => property.SerializationKind switch
    {
        SerializationKind.Primitive => $"writer.Write(this.{property.Name});",
        SerializationKind.String =>
        $@"
        if (this.{property.Name} is null)
            writer.Write(false);
        else
        {{
            writer.Write(true);
            writer.Write(this.{property.Name});
        }}",
        SerializationKind.DateTime => $"writer.Write(this.{property.Name}.ToBinary());",
        _ => $"// Unsupported type: {property.TypeName}"
    };

    private static string GetReadCode(PropertyInfo property) => property.SerializationKind switch
    {
        SerializationKind.Primitive => $"result.{property.Name} = reader.Read{GetPrimitiveReadMethod(property.TypeName)}();",
        SerializationKind.String =>
            $"result.{property.Name} = reader.ReadBoolean() ? reader.ReadString() : null;",
        SerializationKind.DateTime => $"result.{property.Name} = DateTime.FromBinary(reader.ReadInt64());",
        _ => $"// Unsupported type: {property.TypeName}"
    };

    private static string GetPrimitiveReadMethod(string typeName) => typeName switch
    {
        "bool" => "Boolean",
        "byte" => "Byte",
        "sbyte" => "SByte",
        "short" => "Int16",
        "ushort" => "UInt16",
        "int" => "Int32",
        "uint" => "UInt32",
        "long" => "Int64",
        "ulong" => "UInt64",
        "float" => "Single",
        "double" => "Double",
        "decimal" => "Decimal",
        _ => "Int32"
    };

    private static string GetClassModifiers(ClassDeclarationSyntax classDeclaration)
    {
        var modifiers = classDeclaration.Modifiers
            .Where(m => m.IsKind(SyntaxKind.PublicKeyword) ||
                    m.IsKind(SyntaxKind.InternalKeyword) ||
                    m.IsKind(SyntaxKind.AbstractKeyword) ||
                    m.IsKind(SyntaxKind.SealedKeyword) ||
                    m.IsKind(SyntaxKind.StaticKeyword))
            .Select(m => m.Text);

        return string.Join(" ", modifiers);
    }

    private static ImmutableArray<PropertyInfo> GetPublicProperties(INamedTypeSymbol classSymbol)
    {
        var properties = ImmutableArray.CreateBuilder<PropertyInfo>();

        var publicProperties = classSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                    p.GetMethod is not null &&
                    !p.IsStatic &&
                    !p.IsIndexer);

        foreach (var property in publicProperties)
        {
            var typeInfo = property.Type;

            var serializationKind = GetSerializationKind(typeInfo);

            if (serializationKind != SerializationKind.Unsupported)
            {
                properties.Add(new PropertyInfo(
                    property.Name,
                    typeInfo.ToDisplayString(),
                    serializationKind,
                    typeInfo,
                    IsNullablyType(typeInfo))
                );
            }
        }

        return properties.ToImmutable();
    }

    private static SerializationKind GetSerializationKind(ITypeSymbol type)
    {
        if (type.SpecialType == SpecialType.System_Boolean ||
           type.SpecialType == SpecialType.System_Byte ||
           type.SpecialType == SpecialType.System_SByte ||
           type.SpecialType == SpecialType.System_Int16 ||
           type.SpecialType == SpecialType.System_UInt16 ||
           type.SpecialType == SpecialType.System_Int32 ||
           type.SpecialType == SpecialType.System_UInt32 ||
           type.SpecialType == SpecialType.System_Int64 ||
           type.SpecialType == SpecialType.System_UInt64 ||
           type.SpecialType == SpecialType.System_Single ||
           type.SpecialType == SpecialType.System_Double ||
           type.SpecialType == SpecialType.System_Decimal)
        {
            return SerializationKind.Primitive;
        }

        if (type.SpecialType == SpecialType.System_String)
            return SerializationKind.String;

        if (type.ToDisplayString() == "System.DateTime")
            return SerializationKind.DateTime;


#pragma warning disable S1135 // Track uses of "TODO" tags
                             //TODO: Можно будет добавить другие поддерживаемые типы здесь

        return SerializationKind.Unsupported;
#pragma warning restore S1135 // Track uses of "TODO" tags
    }

    private static bool IsNullablyType(ITypeSymbol typeInfo) => typeInfo.NullableAnnotation == NullableAnnotation.Annotated;

    #region private nested

    private enum SerializationKind
    {
        Primitive,
        String,
        DateTime,
        Unsupported = 9999
    }

    private sealed class PropertyInfo
    {
        public string Name { get; }
        public string TypeName { get; }
        public SerializationKind SerializationKind { get; }
        public ITypeSymbol TypeSymbol { get; }
        public bool IsNullable { get; }

        public PropertyInfo(
            string name,
            string typeName,
            SerializationKind serializationKind,
            ITypeSymbol typeSymbol,
            bool isNullable)
        {
            Name = name;
            TypeName = typeName;
            SerializationKind = serializationKind;
            TypeSymbol = typeSymbol;
            IsNullable = isNullable;
        }
    }

    private sealed class ClassSerializationInfo
    {
        public string ClassName { get; }
        public string Namespace { get; }
        public string Modifiers { get; }
        public ImmutableArray<PropertyInfo> Properties { get; }
        public string FullTypeName { get; }
        public bool IsPartial { get; }

        public ClassSerializationInfo(
            string className,
            string @namespace,
            string modifiers,
            ImmutableArray<PropertyInfo> properties,
            string fullTypeName,
            bool isPartial)
        {
            ClassName = className;
            Namespace = @namespace;
            Modifiers = modifiers;
            Properties = properties;
            FullTypeName = fullTypeName;
            IsPartial = isPartial;
        }
    }
    #endregion
}
